const cards = [
    {
        id: "1",
        name: "Tiwi",
        image: "https://i.imgur.com/buvekGN.png",
        banner: "https://i.imgur.com/5MFCQOo.png",
        keywords: "tiwi, Reggio Emilia", 
        anno: "2018/2019",
        pillColor: "#16c958",
        cardDesc: "Tiwi è un azienda di design che ha l'obiettivo di spiegare concetti complessi in un modo semplice. Tiwi unisce parole e immagini per creare video e illustrazioni fantastici.",
        date: "2019-01-07",
        linkAzienda: "https://www.tiwi.it/it/",
        hasPage: true,
        icon: "🎨",
        fullDesc: "La nostra prima attività di PCTO è stata con Tiwi e a primo impatto sembrava davvero difficile: tiwi è un azienda che lavora molto nell'ambito grafico e non penso di essere molto in quel tipo di cose, ma poi il rappresentante dell'azienda ci ha spiegato l'attività. Non era nulla riguardo allo scrivere codice, ma bensì dovevamo creare una presentazione, un video accattivante per convincere un potenziale datore di lavoro a finanziare il nostro fanta-progetto. Per facilitarci il lavoro ci è stato chiesto di utilizzare progetti o serivizi già esistenti, come per esempio: Spotify, Uber Eats o Tik Tok. Il nostro gruppo ha scelto Amazon Prime, e abbiamo creato un piccolo video animato per mostrarne i punti di forza.",
    },
    {
        id: "2",
        name: "KatanaCa'",
        image: "https://i.imgur.com/FpVg1Rm.png",
        anno: "2018/2019",
        pillColor: "#16c958",
        cardDesc: "KatanaCa' è un agenzia immobiliare 2.0 che si concentra sulle richieste del cliente per poter trovare la casa perfetta per lui, tramite il loro sito interattivo.",
        date: "2019-01-10",
        linkAzienda: "https://katanaca.com/",
        hasPage: true,

    },
    {
        id: "3",
        name: "Energy Way",
        image: "https://i.imgur.com/2B7M31d.png",
        anno: "2018/2019",
        pillColor: "#16c958",
        cardDesc: "Energy Way è un azienda di Modena che lavora nel campo del data science e ottimizzazione dei processi aziendali.",
        date: "2019-01-14",
        linkAzienda: "https://ammagamma.com/",
        hasPage: true,
    },
    {
        id: "4",
        name: "Webranking",
        image: "https://i.imgur.com/d31VlHS.png",
        anno: "2018/2019",
        pillColor: "#16c958",
        cardDesc: "Webranking è una grande azienda italiana che si occupa di SEO e ha grandi collaboratori anche in ambito internazionale.",
        date: "2019-01-17",
        linkAzienda: "https://webranking.it/",
        hasPage: true,
    },
    {
        id: "5",
        name: "Errevi System",
        image: "https://i.imgur.com/8YuwN8D.png",
        anno: "2018/2019",
        pillColor: "#16c958",
        cardDesc: "Errevi System è un'azienda locale che si occupa di cybersecurity e soluzioni aziendali in campo informatico.",
        date: "2019-01-21",
        linkAzienda: "https://errevi.com/",
        hasPage: true,
    },
    {
        id: "6",
        name: "Monta Smonta",
        image: "https://i.imgur.com/VaCsPXq.png",
        anno: "2018/2019",
        pillColor: "#16c958",
        cardDesc: "Un progetto scolastico con l'obbiettivo di insegnare le basi di come si approccia l'hardware del computer.",
        date: "2019-03-02",
        hasPage: true,
    },
    {
        id: "7",
        name: "INFO.HTML",
        image: "https://i.imgur.com/VMI08Zv.png",
        anno: "2018/2019",
        pillColor: "#16c958",
        cardDesc: "Un progetto scolastico che consiste nell'insegnare le basi della programmazione ai ragazzini di una scuola media locale.",
        date: "2019-04-17",
        hasPage: true,
    },
    {
        id: "8",
        name: "CNA",
        image: "https://i.imgur.com/FqyINuL.png",
        anno: "2019/2020",
        pillColor: "#ba39e6",
        cardDesc: "In mancanza dell'esperienza in azienda abbiamo ascoltato diverse presentazioni sui vari aspetti del mondo del lavoro grazie all'azienda CNA.",
        date: "2020-05-18",
        linkAzienda: "https://www.cnare.it/",
        hasPage: true,
    },
    {
        id: "9",
        name: "GSTPCTO",
        image: "https://i.imgur.com/1c4fjIF.png",
        anno: "Personale",
        pillColor: "#34a8eb",
        github: "https://github.com/gstpcto/gst-pcto-client",
        cardDesc: "Il progetto finale che racchiude tutta la nostra esperienza come web-dev. Un progetto che si propone di gestire in modo semplice e digitale il PCTO per la scuola",
        date: "2021-03-22",
        hasPage: false,
    },
    {
        id: "10",
        name: "Unicode",
        image: "https://i.imgur.com/PWULBD9.png",
        anno: "2020/2021",
        pillColor: "#f2e33d",
        cardDesc: "Unicode un'azienda che lavora con ambiente Microsoft e con il linguaggio C#. Quest'azienda offre soluzioni software per aziende e privati.",
        date: "2020-11-27",
        linkAzienda: "https://www.unicode.it/",
        hasPage: true,
    },
    {
        id: "11",
        name: "Orientamento",
        image: "https://i.imgur.com/k65mFgj.png",
        anno: "Orientamento",
        pillColor: "#eb4034",
        cardDesc: "Le numerose attività di orientamento che abbiamo fatto quest'anno.",
        date: "2021-04-30",
        hasPage: true,
    },
    {
        id: "12",
        name: "Coffee Counter",
        image: "https://i.imgur.com/sWjwmY9.png",
        anno: "Personale",
        pillColor: "#99681d",
        github: "https://github.com/IlSassone/coffee-counter",
        cardDesc: "La benzina del programmatore è il caffè, ed ecco qui una semplice web app che conta quanti caffè ho bevuto.",
        date: "2021-04-30",
        hasPage: false,
    },
    
]

module.exports = cards


